services:
  api:
    user: bun
    image: oven/bun:1.1.18
    restart: unless-stopped
    working_dir: /usr/src/app
    command: sh -c "bun install && bun start"
    ports:
      - '5000:5000'
    volumes:
      - ./:/usr/src/app

  node:
    user: node
    image: node:latest
    restart: no
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /home/redacted/.npmrc:/home/node/.npmrc
